import Link from "next/link";
import { repos, phases, protocols, dimensions, evidence } from "../data/project";

const A=({href,children}:{href:string,children:React.ReactNode})=><a className="link" href={href} target="_blank" rel="noreferrer">{children}</a>;

export function Nav(){return <header className="nav"><div className="container navin"><Link href="/" className="brand">ATF<span>/</span>AGENT-PAY</Link><nav><Link href="/#why">Why</Link><Link href="/architecture">Architecture</Link><Link href="/#use-cases">Use Cases</Link><Link href="/protocols">Interoperability</Link><Link href="/verification">Engineering</Link><Link href="/post-v2">Roadmap</Link><A href="https://github.com/Agentic-Trust-Foundation">GitHub ↗</A></nav></div></header>}

export function Shell({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <><Nav/><main className="container page"><div className="kicker">{kicker}</div><h1>{title}</h1>{children}</main><footer className="footer"><div className="container">Evidence-driven portfolio · Agentic Trust Foundation · 2026</div></footer></>}

export function Home(){return <><Nav/><main>
<section className="hero container">
<div className="eyebrow">AGENTIC TRUST FOUNDATION / ATF + AGENT-PAY</div>
<h1>The Agentic Internet needs a <em>trust layer.</em></h1>
<p className="lead">Agents are becoming capable of acting for us — buying, booking, paying, accessing services, and working with other agents. The hard problem is not only what an agent can do. It is <strong>what it is allowed to do on our behalf.</strong></p>
<div className="actions"><Link className="button primary" href="#why">Why this matters</Link><Link className="button" href="/architecture">How it works</Link></div>
</section>

<section id="why" className="section alt"><div className="container"><SectionHead t="Give your agent the ability to act — not unlimited authority." s="The future of agents is not just conversation. Agents will take actions in the real world. That requires a clear boundary between capability and authority."/><div className="split"><div><p className="lead">You should be able to tell an agent what it may do, where it may act, how much it may spend, and when it must come back to you.</p><div className="cards">{["What can this agent do?","Which services can it access?","What actions are allowed?","How much authority was delegated?","What limits and policies apply?","When must the user approve?","Can the authority be revoked?"].map(x=><div className="card" key={x}><span className="dot"/>{x}</div>)}</div></div><div className="callout"><b>The core idea</b><p>Human sets the authority. Agent performs the work inside those boundaries. When an action crosses a boundary, the agent stops and asks.</p></div></div></div></section>

<section className="section container"><SectionHead t="A trust layer between intention and action." s="Authority should travel with the action — explicitly, narrowly, and with enough context to make the decision auditable."/><div className="architecture"><Node title="HUMAN / PRINCIPAL" body="Intent · identity · responsibility"/><div className="arrow">↓</div><Node title="DELEGATION" body="What the agent may do · scope · purpose · lifetime"/><div className="arrow">↓</div><Node title="AUTHORIZATION + POLICY" body="Resources · actions · limits · conditions · approval rules"/><div className="arrow">↓</div><Node title="AGENT" body="Acts autonomously inside the delegated authority"/><div className="arrow">↓</div><Node title="SERVICE / COMMERCE / PAYMENT" body="The real-world action happens here"/><div className="arrow">↓</div><Node title="AUDIT + REVOCATION" body="What happened · why · under whose authority · what can be stopped"/></div></section>

<section className="section alt"><div className="container"><SectionHead t="Let the agent handle the small things." s="A useful agent should not ask for permission every few minutes. It should handle routine work automatically and escalate only when the risk or authority boundary requires you."/><div className="cards"><div className="card"><div className="kicker">ROUTINE</div><h3>Agent acts</h3><p className="muted">Everyday tasks inside the user's policy can happen without interrupting the user.</p></div><div className="card"><div className="kicker">LOW RISK</div><h3>Act + notify</h3><p className="muted">The agent completes the action and keeps the user informed.</p></div><div className="card"><div className="kicker">HIGH RISK</div><h3>Ask first</h3><p className="muted">The agent pauses when an action is outside its delegated boundary or needs explicit approval.</p></div><div className="card"><div className="kicker">FORBIDDEN</div><h3>Deny</h3><p className="muted">Authentication alone never gives an agent unlimited authority.</p></div></div></div></section>

<section className="section container"><SectionHead t="Your agent can have a wallet — without owning your money." s="Financial autonomy needs the same principle: give the agent controlled spending authority, not unrestricted access to the user's primary financial authority."/><div className="split"><div><div className="cards"><div className="card"><h3>Budget</h3><p className="muted">Define how much the agent can spend.</p></div><div className="card"><h3>Limits</h3><p className="muted">Set per-transaction, daily, or contextual limits.</p></div><div className="card"><h3>Merchant &amp; category rules</h3><p className="muted">Allow approved merchants or categories and block restricted ones.</p></div><div className="card"><h3>Approval</h3><p className="muted">Require the user to confirm sensitive or high-value transactions.</p></div></div></div><div className="callout"><div className="kicker">AGENT-PAY</div><h3>Controlled financial authority</h3><p>An agent can operate with a wallet or dedicated payment instrument such as a virtual card, while policy remains between the agent and the user's authority.</p><p><strong>The agent gets spending authority — not ownership of the user's money.</strong></p></div></div></section>

<section className="section alt"><div className="container"><SectionHead t="When the boundary is crossed, the human comes back into the loop." s="The agent does not need to ask about every coffee or calendar change. It asks when the decision matters."/><div className="callout approval"><div className="kicker">EXAMPLE</div><h3>This purchase requires your approval.</h3><p>Amount: $850 · Merchant: New merchant · Reason: Outside the agent's normal spending policy</p><div className="actions"><button className="button primary" type="button">Approve</button><button className="button" type="button">Reject</button></div></div><p className="lead center">The user defines the boundary once. The agent can perform hundreds of small actions within it — and return for a final decision when necessary.</p></div></section>

<section id="use-cases" className="section container"><SectionHead t="From everyday tasks to autonomous commerce." s="The same authority model can govern very different kinds of agentic action."/><div className="cards">{[["Everyday assistant","Manage routine tasks, bookings, messages and services within explicit permissions."],["Shopping agent","Find and purchase products within budget, merchant and category policies."],["Travel agent","Search, book and manage travel while escalating expensive or exceptional decisions."],["Enterprise agent","Access internal APIs and systems only for the resources and operations delegated to it."],["Cloud / infrastructure agent","Create, change or scale infrastructure inside approved environments, limits and policies."],["Agent → Agent","Delegate a bounded task without silently transferring the principal's full authority."]].map(([t,b])=><div className="card" key={t}><h3>{t}</h3><p className="muted">{b}</p></div>)}</div></div></section>

<section className="section alt"><div className="container"><SectionHead t="The principle is simple." s="Autonomy should increase what an agent can do — not remove the human's control over what it is allowed to do."/><div className="cards"><div className="card"><h3>Explicit</h3><p className="muted">Authority is granted deliberately.</p></div><div className="card"><h3>Scoped</h3><p className="muted">Authority covers specific actions, resources and contexts.</p></div><div className="card"><h3>Policy-controlled</h3><p className="muted">Rules determine what can happen automatically.</p></div><div className="card"><h3>Observable</h3><p className="muted">Actions and decisions remain traceable.</p></div><div className="card"><h3>Revocable</h3><p className="muted">Authority can be withdrawn.</p></div></div><div className="callout"><b>Human sets the authority. Agent executes the work.</b><p>That is the trust layer for the Agentic Internet.</p></div></div></section>

<section className="section container"><SectionHead t="Built for an open agentic ecosystem." s="ATF is designed to connect identity, delegation, authorization, policy, trust, execution and audit without pretending to replace the protocols that already solve specific parts of the stack."/><div className="cards"><div className="card"><h3>ATF</h3><p className="muted">Trust, delegation and access: the authority layer for agentic actions.</p></div><div className="card"><h3>Agent-Pay</h3><p className="muted">Financial control: budgets, payment instruments, provider rules, approvals, transactions and audit.</p></div><div className="card"><h3>Existing protocols</h3><p className="muted">Identity, APIs, agent communication, commerce and payment protocols remain part of the ecosystem and retain their own native semantics.</p></div></div><div className="actions"><Link className="button primary" href="/architecture">Explore the architecture</Link><Link className="button" href="/protocols">Explore interoperability</Link></div></div></section>

</main><footer className="footer"><div className="container">Agentic Trust Foundation · Trust, delegation and controlled access for the Agentic Internet</div></footer></>}

function Stat({n,label}:{n:string,label:string}){return <div className="stat"><b>{n}</b><span>{label}</span></div>}
function Node({title,body}:{title:string,body:string}){return <div className="node"><b>{title}</b><span>{body}</span></div>}
function SectionHead({t,s}:{t:string,s:string}){return <div className="section-head"><div className="kicker">SYSTEM / EVIDENCE</div><h2>{t}</h2><p>{s}</p></div>}
function RepoCard({r}:{r:(typeof repos)[number]}){return <div className="repo-card"><div className="repo-top"><strong>{r.name}</strong></div><p>{r.role}</p><div className="status">{r.status}</div><code>{r.sha.slice(0,12)}</code><A href={r.url}>Open repository ↗</A></div>}

export function Architecture(){return <Shell kicker="ARCHITECTURE" title="Authority, integration, execution."><p className="lead">The architecture keeps trust and delegated authority upstream, while service adapters and payment systems consume that evidence without expanding it.</p><div className="diagram large"><Node title="Principal / Agent" body="Identity + credentials"/><div className="arrow">↓</div><Node title="ATF V2" body="Delegation · authorization · trust · consent · revocation · provenance · auditability"/><div className="arrow">↓</div><Node title="Site Adapter V1" body="Origin binding · capability/profile discovery · authenticated interaction · idempotency"/><div className="arrow">↓</div><Node title="Agent-Pay V2" body="Financial policy · budget · approval · instruments · provider operation · transaction · ledger"/><div className="arrow">↓</div><Node title="Provider / Local Profile" body="Execution, settlement, reconciliation, target-environment controls"/></div><div className="callout"><b>Core invariant</b><p>ATF establishes authority; downstream systems execute within that authority. Agent-Pay must never expand upstream ATF authority.</p></div></Shell>}

export function Phases(){return <Shell kicker="ENGINEERING JOURNEY" title="V1 → V2 → finalization."><p className="lead">The current roadmap records Phases 35–43 as complete, with completion defined by implementation evidence rather than documentation alone.</p><div className="phase-list">{phases.map(([n,t])=><article key={n}><div className="phase-num">{n}</div><div><h3>{t}</h3><p>{phaseDesc(n)}</p><span className="tag">COMPLETE — ROADMAP STATUS</span></div></article>)}</div></Shell>}
function phaseDesc(n:string){const d:Record<string,string>={"35":"Canonical financial terms, invariants, representations and validation rules.","36":"Provider-neutral payment instruments, lifecycle boundaries, provider capability contracts and approval semantics.","37":"Commerce-protocol interoperability boundaries and versioned integration contracts.","38":"Deployment-specific profiles, evidence boundaries and production-gating rules.","39":"Security invariants, fail-closed behavior, validation and hardening requirements.","40":"Independent conformance/certification contract and reproducible interoperability evidence.","41":"Release-candidate stabilization, canonicalization and final conformance gates.","42":"ATF V2 final protocol baseline and final cross-repository validation.","43":"Agent-Pay V2 final baseline, final contract runner, test discovery and ATF cross-repository final gate."};return d[n]}

export function Protocols(){return <Shell kicker="INTEROPERABILITY" title="Protocol gap analysis."><p className="lead">The portfolio preserves the distinction between ATF semantics and external protocols' native wire formats. Capability labels below are intentionally framed as analysis dimensions, not universal protocol support claims.</p><div className="matrix-wrap"><table className="matrix"><thead><tr><th>Dimension</th>{protocols.map(p=><th key={p}>{p}</th>)}</tr></thead><tbody>{dimensions.map(d=><tr key={d}><th>{d}</th>{protocols.map(p=><td key={p}>Profile / analysis</td>)}</tr>)}</tbody></table></div><div className="callout"><b>Important</b><p>External protocols remain authoritative for their own wire semantics. The project documentation does not justify claiming that ATF replaces MCP, A2A, OAuth, ARD, AP2, ACP or UCP.</p></div></Shell>}

export function Verification(){return <Shell kicker="VERIFICATION" title="From specification to evidence."><p className="lead">V2 completion is defined as an executable chain: specification/contract, machine-readable representation where applicable, canonical vectors, implementation, tests, CI, and cross-repository verification.</p><div className="verify-grid">{evidence.map((x,i)=><div className="verify" key={x}><b>{String(i+1).padStart(2,"0")}</b><h3>{x}</h3><p>{verificationText(i)}</p></div>)}</div><div className="boundary-grid"><div><b>CI success</b><span>does not equal production evidence</span></div><div><b>Own integration</b><span>does not equal independent adoption</span></div><div><b>Existing verifier</b><span>does not equal independent certification</span></div></div></Shell>}
function verificationText(i:number){return ["Normative contract or protocol specification.","JSON Schema / OpenAPI / machine-readable contract where applicable.","Canonical vectors and fixtures used by validators.","Reference implementation or executable integration.","Tests exercise the intended invariants.","GitHub Actions or equivalent executable validation.","Cross-repository contracts are checked at exact versions.","Artifacts can identify exact revisions without exposing secrets."][i]}

export function Repositories(){return <Shell kicker="REPOSITORY MAP" title="One ecosystem, explicit boundaries."><p className="lead">Current GitHub state was checked on 2026-09-24. Where a supplied historical baseline differed from the current main branch, the current branch was treated as authoritative.</p><div className="repo-grid">{repos.map(r=><RepoCard key={r.name} r={r}/>)}</div></Shell>}

export function PostV2(){return <Shell kicker="POST-V2" title="Enablement, adoption, production evidence."><p className="lead">Post-V2 is an execution program, not a new protocol version. V2 normative semantics remain frozen unless an explicit versioned successor is approved.</p><div className="post-grid"><article><span>PVE-1</span><h2>Ecosystem Enablement</h2><p>Quick starts, examples, profiles, tooling, fixtures and conformance harnesses to make external integration practical.</p><label>Evidence: integration path and executable examples</label></article><article><span>PVE-2</span><h2>Independent Adoption</h2><p>An independently maintained integration must be verified against canonical V2 contracts/vectors with exact-version evidence.</p><label>Status: evidence required for an actual independent implementation</label></article><article><span>PVE-3</span><h2>Production Evidence</h2><p>Real deployment evidence must identify implementation/version, contract/vector set, observed execution and audit evidence.</p><label>Status: deployment-gated; no live-provider claim is implied</label></article></div><div className="callout"><b>Evidence boundary</b><p>Foundation-owned reference implementations and CI establish engineering evidence. They do not by themselves establish independent adoption, production deployment, provider activation, regulatory certification, or target-environment readiness.</p></div></Shell>}
