import Link from "next/link";
import { repos, phases, protocols, dimensions, evidence } from "../data/project";

const A=({href,children}:{href:string,children:React.ReactNode})=><a className="link" href={href} target="_blank" rel="noreferrer">{children}</a>;

export function Nav(){return <header className="nav"><div className="container navin"><Link href="/" className="brand">ATF<span>/</span>AGENT-PAY</Link><nav><Link href="/#why">Why</Link><Link href="/architecture">Architecture</Link><Link href="/#use-cases">Use Cases</Link><Link href="/protocols">Interoperability</Link><Link href="/verification">Engineering</Link><Link href="/post-v2">Roadmap</Link><A href="https://github.com/Agentic-Trust-Foundation">GitHub ↗</A></nav></div></header>}

export function Shell({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <><Nav/><main className="container page"><div className="kicker">{kicker}</div><h1>{title}</h1>{children}</main><footer className="footer"><div className="container">Evidence-driven portfolio · Agentic Trust Foundation · 2026</div></footer></>}

export function Home(){return <><Nav/><main>
<section className="hero container">
<div className="eyebrow">AGENTIC TRUST FOUNDATION / ATF + AGENT-PAY</div>
<h1>The Agentic Internet needs a <em>trust layer.</em></h1>
<p className="lead">Agents are becoming able to discover services, call APIs, delegate work, and initiate transactions. The hard problem is not only what an agent can do — it is <strong>who gave it authority, what that authority covers, under which policy, and how the action can be controlled and audited.</strong></p>
<div className="actions"><Link className="button primary" href="#why">Why this exists</Link><Link className="button" href="/architecture">See the architecture</Link></div>
<div className="hero-grid"><Stat n="ATF V2" label="Trust / delegation / access layer"/><Stat n="Agent-Pay V2" label="Financial control layer"/><Stat n="35→43" label="Implemented finalization phases"/><Stat n="CI ≠ Prod" label="Evidence boundary"/></div>
</section>
<section id="why" className="section alt"><div className="container"><SectionHead t="The problem" s="The emerging agentic stack has many protocols and tools. The missing question is how their authority fits together."/><div className="split"><div><p className="lead">An agent may authenticate to one service, receive delegated access from a principal, discover another capability, call a third-party API, and eventually spend money. Without a coherent authority model, it becomes difficult to answer:</p><div className="cards">{["Who authorized this agent?","On whose behalf is it acting?","What exactly was delegated?","Which resources and actions are in scope?","When does the authority expire or get revoked?","Was approval required before money or sensitive actions moved?","Can the resulting action be traced and audited?"].map(x=><div className="card" key={x}><span className="dot"/>{x}</div>)}</div></div><div className="callout"><b>The gap we are targeting</b><p>Not a lack of protocols. A lack of a coherent control layer connecting identity, delegation, authorization, policy, trust, execution and audit across agentic interactions.</p></div></div></div></section>
<section className="section container"><SectionHead t="Our answer" s="A layered control model that separates authority from execution."/><div className="architecture"><Node title="IDENTITY" body="Principal · user · agent · service"/><div className="arrow">↓</div><Node title="DELEGATION" body="Scope · audience · purpose · lifetime · revocation"/><div className="arrow">↓</div><Node title="AUTHORIZATION + POLICY" body="Allowed actions · resources · constraints · approval"/><div className="arrow">↓</div><Node title="TRUST + PROVENANCE" body="Evidence · context · reputation · traceability"/><div className="arrow">↓</div><Node title="EXECUTION" body="API · service · another agent · commerce · payment"/><div className="arrow">↓</div><Node title="AUDIT" body="Decision · transaction · evidence · reconciliation"/></div></section>
<section className="section alt"><div className="container"><SectionHead t="ATF and Agent-Pay" s="Two connected layers with different responsibilities."/><div className="cards"><div className="card"><div className="kicker">ATF</div><h3>Trust, delegation &amp; access</h3><p className="muted">Defines identity, delegated authority, authorization, consent, revocation, provenance and auditability.</p></div><div className="card"><div className="kicker">AGENT-PAY</div><h3>Financial control &amp; execution</h3><p className="muted">Applies financial policy around budgets, limits, approvals, instruments, providers, transactions, ledger state and audit.</p></div><div className="callout"><b>Core invariant</b><p>ATF establishes authority. Downstream systems execute within that authority. Agent-Pay must never expand upstream ATF authority.</p></div></div></div></section>
<section id="use-cases" className="section container"><SectionHead t="What can be built with it?" s="Infrastructure for controlled agentic actions — not an agent framework itself."/><div className="cards">{[["Agent → API","Narrowly scoped access to specific APIs, resources and operations."],["Agent → Purchase","Purchasing within explicit budget, merchant policy, approval rules and payment instruments."],["Agent → Booking","Bookings under delegated authority and auditable constraints."],["Agent → Agent","Bounded delegation without silently transferring the principal's full authority."],["Agent → Cloud / Infra","Controlled deployment, scaling or restart under explicit scope and policy."],["Enterprise Agent","Identity, delegation, authorization and audit across internal and external services."]].map(([t,b])=><div className="card" key={t}><h3>{t}</h3><p className="muted">{b}</p></div>)}</div></section>
<section className="section alt"><div className="container"><SectionHead t="What agents must not be able to do" s="Safety and authority boundaries are part of the architecture."/><div className="cards">{["Inherit all of a principal's authority merely because they authenticated.","Expand delegated authority by passing it to another agent without explicit rules.","Treat payment capability as permission for unrestricted financial activity.","Treat technical verification as proof of production adoption.","Redefine the semantics of an external protocol through an adapter.","Hide authority, policy or provenance behind an opaque execution step."].map(x=><div className="card" key={x}><span className="dot"/>{x}</div>)}</div><div className="callout"><b>Design principle</b><p>Authority must be explicit, scoped, observable and revocable.</p></div></div></section>
<section className="section container"><SectionHead t="Interoperability, not replacement" s="ATF sits across the agentic stack while preserving the native semantics of protocols that solve specific problems."/><div className="cards">{protocols.map(p=><div className="card" key={p}><strong>{p}</strong><p className="muted">Analyzed as part of the interoperability model; its own wire semantics remain authoritative.</p></div>)}</div><div className="callout"><b>Boundary</b><p>ATF is not an LLM, agent framework, API gateway, OAuth replacement, MCP replacement, A2A replacement, payment processor, bank, merchant, or regulatory certification.</p></div></section>
<section className="section alt"><div className="container"><SectionHead t="What we actually built" s="The project is backed by an inspectable engineering chain rather than a conceptual diagram alone."/><div className="evidence-chain">{evidence.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</div>)}</div><div className="actions"><Link className="button primary" href="/verification">Inspect verification</Link><Link className="button" href="/phases">See engineering journey</Link></div></div></section>
<section className="section container"><SectionHead t="Engineering evidence" s="Phases 35–43 record the implementation and finalization path behind the current V2 baseline."/><div className="timeline">{phases.map(([n,t])=><div className="phase" key={n}><span>{n}</span><div><strong>{t}</strong><small>Implementation / tests / CI / cross-repository verification</small></div></div>)}</div></section>
<section className="section alt"><div className="container"><SectionHead t="Explore the implementation" s="The repositories are evidence of the system — not the system's purpose."/><div className="repo-grid">{repos.map(r=><RepoCard key={r.name} r={r}/>)}</div></div></section>
<section className="section container"><SectionHead t="Where this goes next" s="V2 freezes the normative baseline; the next step is ecosystem enablement, independent implementations and real deployment evidence."/><div className="cards"><div className="card"><h3>Enablement</h3><p className="muted">Examples, profiles, fixtures, tooling and conformance harnesses for practical integration.</p></div><div className="card"><h3>Independent adoption</h3><p className="muted">Validate independently maintained implementations against canonical contracts and vectors.</p></div><div className="card"><h3>Production evidence</h3><p className="muted">Connect implementation/version, contract/vector set, observed execution and audit evidence to real deployments.</p></div></div></section>
</main><footer className="footer"><div className="container">Agentic Trust Foundation · <A href="https://github.com/Agentic-Trust-Foundation">GitHub organization</A> · V2 engineering baseline</div></footer></>}
function Stat({n,label}:{n:string,label:string}){return <div className="stat"><b>{n}</b><span>{label}</span></div>}
function Node({title,body}:{title:string,body:string}){return <div className="node"><b>{title}</b><span>{body}</span></div>}
function SectionHead({t,s}:{t:string,s:string}){return <div className="section-head"><div className="kicker">SYSTEM / EVIDENCE</div><h2>{t}</h2><p>{s}</p></div>}
function RepoCard({r}:{r:(typeof repos)[number]}){return <div className="repo-card"><div className="repo-top"><strong>{r.name}</strong></div><p>{r.role}</p><div className="status">{r.status}</div><code>{r.sha.slice(0,12)}</code><A href={r.url}>Open repository ↗</A></div>}

export function Architecture(){return <Shell kicker="ARCHITECTURE" title="Authority, integration, execution."><p className="lead">The architecture keeps trust and delegated authority upstream, while service adapters and payment systems consume that evidence without expanding it.</p><div className="diagram large"><Node title="Principal / Agent" body="Identity + credentials"/><div className="arrow">↓</div><Node title="ATF V2" body="Delegation · authorization · trust · consent · revocation · provenance · auditability"/><div className="arrow">↓</div><Node title="Site Adapter V1" body="Origin binding · capability/profile discovery · authenticated interaction · idempotency"/><div className="arrow">↓</div><Node title="Agent-Pay V2" body="Financial policy · budget · approval · instruments · provider operation · transaction · ledger"/><div className="arrow">↓</div><Node title="Provider / Local Profile" body="Execution, settlement, reconciliation, target-environment controls"/></div><div className="callout"><b>Core invariant</b><p>ATF establishes authority; downstream systems execute within that authority. Agent-Pay must never expand upstream ATF authority.</p></div></Shell>}

export function Phases(){return <Shell kicker="ENGINEERING JOURNEY" title="V1 → V2 → finalization."><p className="lead">The current roadmap records Phases 35–43 as complete, with completion defined by implementation evidence rather than documentation alone.</p><div className="phase-list">{phases.map(([n,t])=><article key={n}><div className="phase-num">{n}</div><div><h3>{t}</h3><p>{phaseDesc(n)}</p><span className="tag">COMPLETE — ROADMAP STATUS</span></div></article>)}</div></Shell>}
function phaseDesc(n:string){const d:Record<string,string>={"35":"Canonical financial terms, invariants, representations and validation rules.","36":"Provider-neutral payment instruments, lifecycle boundaries, provider capability contracts and approval semantics.","37":"Commerce-protocol interoperability boundaries and versioned integration contracts.","38":"Deployment-specific profiles, evidence boundaries and production-gating rules.","39":"Security invariants, fail-closed behavior, validation and hardening requirements.","40":"Independent conformance/certification contract and reproducible interoperability evidence.","41":"Release-candidate stabilization, canonicalization and final conformance gates.","42":"ATF V2 final protocol baseline and final cross-repository validation.","43":"Agent-Pay V2 final baseline, final contract runner, test discovery and ATF cross-repository final gate."};return d[n]}

export function Protocols(){return <Shell kicker="INTEROPERABILITY" title="Protocol gap analysis."><p className="lead">The portfolio preserves the distinction between ATF semantics and external protocols' native wire formats. Capability labels below are intentionally framed as analysis dimensions, not universal protocol support claims.</p><div className="matrix-wrap"><table className="matrix"><thead><tr><th>Dimension</th>{protocols.map(p=><th key={p}>{p}</th>)}</tr></thead><tbody>{dimensions.map(d=><tr key={d}><th>{d}</th>{protocols.map(p=><td key={p}>Profile / analysis</td>)}</tr>)}</tbody></table></div><div className="callout"><b>Important</b><p>External protocols remain authoritative for their own wire semantics. The project documentation does not justify claiming that ATF replaces MCP, A2A, OAuth, ARD, AP2, ACP or UCP.</p></div></Shell>}

export function Verification(){return <Shell kicker="VERIFICATION" title="From specification to evidence."><p className="lead">V2 completion is defined as an executable chain: specification/contract, machine-readable representation where applicable, canonical vectors, implementation, tests, CI, and cross-repository verification.</p><div className="verify-grid">{evidence.map((x,i)=><div className="verify" key={x}><b>{String(i+1).padStart(2,"0")}</b><h3>{x}</h3><p>{verificationText(i)}</p></div>)}</div><div className="boundary-grid"><div><b>CI success</b><span>does not equal production evidence</span></div><div><b>Own integration</b><span>does not equal independent adoption</span></div><div><b>Existing verifier</b><span>does not equal independent certification</span></div></div></Shell>}
function verificationText(i:number){return ["Normative contract or protocol specification.","JSON Schema / OpenAPI / machine-readable contract where applicable.","Canonical vectors and fixtures used by validators.","Reference implementation or executable integration.","Tests exercise the intended invariants.","GitHub Actions or equivalent executable validation.","Cross-repository contracts are checked at exact versions.","Artifacts can identify exact revisions without exposing secrets."][i]}

export function Repositories(){return <Shell kicker="REPOSITORY MAP" title="One ecosystem, explicit boundaries."><p className="lead">Current GitHub state was checked on 2026-09-24. Where a supplied historical baseline differed from the current main branch, the current branch was treated as authoritative.</p><div className="repo-grid">{repos.map(r=><RepoCard key={r.name} r={r}/>)}</div></Shell>}

export function PostV2(){return <Shell kicker="POST-V2" title="Enablement, adoption, production evidence."><p className="lead">Post-V2 is an execution program, not a new protocol version. V2 normative semantics remain frozen unless an explicit versioned successor is approved.</p><div className="post-grid"><article><span>PVE-1</span><h2>Ecosystem Enablement</h2><p>Quick starts, examples, profiles, tooling, fixtures and conformance harnesses to make external integration practical.</p><label>Evidence: integration path and executable examples</label></article><article><span>PVE-2</span><h2>Independent Adoption</h2><p>An independently maintained integration must be verified against canonical V2 contracts/vectors with exact-version evidence.</p><label>Status: evidence required for an actual independent implementation</label></article><article><span>PVE-3</span><h2>Production Evidence</h2><p>Real deployment evidence must identify implementation/version, contract/vector set, observed execution and audit evidence.</p><label>Status: deployment-gated; no live-provider claim is implied</label></article></div><div className="callout"><b>Evidence boundary</b><p>Foundation-owned reference implementations and CI establish engineering evidence. They do not by themselves establish independent adoption, production deployment, provider activation, regulatory certification, or target-environment readiness.</p></div></Shell>}
