import Link from "next/link";
import { repos, phases, protocols, dimensions, evidence } from "../data/project";

const A=({href,children}:{href:string,children:React.ReactNode})=><a className="link" href={href} target="_blank" rel="noreferrer">{children}</a>;

export function Nav(){return <header className="nav"><div className="container navin"><Link href="/" className="brand">ATF<span>/</span>PORTFOLIO</Link><nav><Link href="/architecture">Architecture</Link><Link href="/phases">Phases</Link><Link href="/protocols">Protocols</Link><Link href="/verification">Verification</Link><Link href="/repositories">Repositories</Link><Link href="/post-v2">Post-V2</Link></nav></div></header>}

export function Shell({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <><Nav/><main className="container page"><div className="kicker">{kicker}</div><h1>{title}</h1>{children}</main><footer className="footer"><div className="container">Evidence-driven portfolio · Agentic Trust Foundation · 2026</div></footer></>}

export function Home(){return <><Nav/><main>
<section className="hero container"><div className="eyebrow">ENGINEERING PORTFOLIO / ATF + AGENT-PAY</div><h1>Trust, Delegation &amp; Access for the <em>Agentic Internet.</em></h1><p className="lead">A multi-repository engineering body of work covering authority semantics, delegated access, financial controls, interoperability, reproducible conformance, and deployment evidence.</p><div className="actions"><Link className="button primary" href="/architecture">Explore architecture</Link><Link className="button" href="/verification">See verification</Link></div><div className="hero-grid"><Stat n="V2" label="Final protocol baseline"/><Stat n="35→43" label="Finalization sequence"/><Stat n="6" label="Tracked repositories"/><Stat n="CI ≠ Prod" label="Evidence boundary"/></div></section>
<section className="section container"><SectionHead t="The system" s="A protocol-first separation of authority from execution."/><div className="architecture"><Node title="AGENTIC INTERNET" body="Agents · services · commerce"/><div className="arrow">↓</div><Node title="AGENTIC TRUST FOUNDATION" body="Identity · delegation · authorization · trust · reputation"/><div className="arrow">↓</div><Node title="AGENT-PAY" body="Policy · approvals · instruments · transactions · ledger · audit"/><div className="arrow">↓</div><Node title="AGENT COMMERCE" body="APIs · merchants · providers · other agents"/></div></section>
<section className="section alt"><div className="container"><SectionHead t="Engineering journey" s="From frozen V1 foundations to V2 finalization."/><div className="timeline">{phases.map(([n,t])=><div className="phase" key={n}><span>{n}</span><div><strong>{t}</strong><small>Complete per project roadmap</small></div></div>)}</div></div></section>
<section className="section container"><SectionHead t="What was engineered" s="The portfolio focuses on artifacts and verification, not marketing claims."/><div className="cards">{["Protocol design","Distributed boundaries","Delegation & authorization","Financial semantics","Virtual card architecture","Interoperability","Canonical vectors","CI / cross-repo conformance","Security hardening","Deployment profiles","Evidence architecture","Governance"].map(x=><div className="card" key={x}><span className="dot"/> {x}</div>)}</div></section>
<section className="section alt"><div className="container split"><div><SectionHead t="Evidence model" s="Each important claim should trace back to an inspectable artifact."/><p className="muted">Feature → repository → commit → specification → schema → vectors → implementation → tests → CI. Production and adoption claims remain separately gated.</p></div><div className="evidence-chain">{evidence.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</div>)}</div></div></section>
<section className="section container"><SectionHead t="Repositories" s="The ecosystem is intentionally split by responsibility."/><div className="repo-grid">{repos.map(r=><RepoCard key={r.name} r={r}/>)}</div></section>
</main><footer className="footer"><div className="container">Built as a technical portfolio · <A href="https://github.com/Agentic-Trust-Foundation">GitHub organization</A></div></footer></>}

function Stat({n,label}:{n:string,label:string}){return <div className="stat"><b>{n}</b><span>{label}</span></div>}
function Node({title,body}:{title:string,body:string}){return <div className="node"><b>{title}</b><span>{body}</span></div>}
function SectionHead({t,s}:{t:string,s:string}){return <div className="section-head"><div className="kicker">SYSTEM / EVIDENCE</div><h2>{t}</h2><p>{s}</p></div>}
function RepoCard({r}:{r:(typeof repos)[number]}){return <div className="repo-card"><div className="repo-top"><strong>{r.name}</strong><span className={r.visibility==="Public"?"public":"private"}>{r.visibility}</span></div><p>{r.role}</p><div className="status">{r.status}</div><code>{r.sha.slice(0,12)}</code><A href={r.url}>Open repository ↗</A></div>}

export function Architecture(){return <Shell kicker="ARCHITECTURE" title="Authority, integration, execution."><p className="lead">The architecture keeps trust and delegated authority upstream, while service adapters and payment systems consume that evidence without expanding it.</p><div className="diagram large"><Node title="Principal / Agent" body="Identity + credentials"/><div className="arrow">↓</div><Node title="ATF V2" body="Delegation · authorization · trust · consent · revocation · provenance · auditability"/><div className="arrow">↓</div><Node title="Site Adapter V1" body="Origin binding · capability/profile discovery · authenticated interaction · idempotency"/><div className="arrow">↓</div><Node title="Agent-Pay V2" body="Financial policy · budget · approval · instruments · provider operation · transaction · ledger"/><div className="arrow">↓</div><Node title="Provider / Local Profile" body="Execution, settlement, reconciliation, target-environment controls"/></div><div className="callout"><b>Core invariant</b><p>ATF establishes authority; downstream systems execute within that authority. Agent-Pay must never expand upstream ATF authority.</p></div></Shell>}

export function Phases(){return <Shell kicker="ENGINEERING JOURNEY" title="V1 → V2 → finalization."><p className="lead">The current roadmap records Phases 35–43 as complete, with completion defined by implementation evidence rather than documentation alone.</p><div className="phase-list">{phases.map(([n,t])=><article key={n}><div className="phase-num">{n}</div><div><h3>{t}</h3><p>{phaseDesc(n)}</p><span className="tag">COMPLETE — ROADMAP STATUS</span></div></article>)}</div></Shell>}
function phaseDesc(n:string){const d:Record<string,string>={"35":"Canonical financial terms, invariants, representations and validation rules.","36":"Provider-neutral payment instruments, lifecycle boundaries, provider capability contracts and approval semantics.","37":"Commerce-protocol interoperability boundaries and versioned integration contracts.","38":"Deployment-specific profiles, evidence boundaries and production-gating rules.","39":"Security invariants, fail-closed behavior, validation and hardening requirements.","40":"Independent conformance/certification contract and reproducible interoperability evidence.","41":"Release-candidate stabilization, canonicalization and final conformance gates.","42":"ATF V2 final protocol baseline and final cross-repository validation.","43":"Agent-Pay V2 final baseline, final contract runner, test discovery and ATF cross-repository final gate."};return d[n]}

export function Protocols(){return <Shell kicker="INTEROPERABILITY" title="Protocol gap analysis."><p className="lead">The portfolio preserves the distinction between ATF semantics and external protocols' native wire formats. Capability labels below are intentionally framed as analysis dimensions, not universal protocol support claims.</p><div className="matrix-wrap"><table className="matrix"><thead><tr><th>Dimension</th>{protocols.map(p=><th key={p}>{p}</th>)}</tr></thead><tbody>{dimensions.map(d=><tr key={d}><th>{d}</th>{protocols.map(p=><td key={p}>Profile / analysis</td>)}</tr>)}</tbody></table></div><div className="callout"><b>Important</b><p>External protocols remain authoritative for their own wire semantics. The project documentation does not justify claiming that ATF replaces MCP, A2A, OAuth, ARD, AP2, ACP or UCP.</p></div></Shell>}

export function Verification(){return <Shell kicker="VERIFICATION" title="From specification to evidence."><p className="lead">V2 completion is defined as an executable chain: specification/contract, machine-readable representation where applicable, canonical vectors, implementation, tests, CI, and cross-repository verification.</p><div className="verify-grid">{evidence.map((x,i)=><div className="verify" key={x}><b>{String(i+1).padStart(2,"0")}</b><h3>{x}</h3><p>{verificationText(i)}</p></div>)}</div><div className="boundary-grid"><div><b>CI success</b><span>does not equal production evidence</span></div><div><b>Own integration</b><span>does not equal independent adoption</span></div><div><b>Existing verifier</b><span>does not equal independent certification</span></div></div></Shell>}
function verificationText(i:number){return ["Normative contract or protocol specification.","JSON Schema / OpenAPI / machine-readable contract where applicable.","Canonical vectors and fixtures used by validators.","Reference implementation or executable integration.","Tests exercise the intended invariants.","GitHub Actions or equivalent executable validation.","Cross-repository contracts are checked at exact versions.","Artifacts can identify exact revisions without exposing secrets."][i]}

export function Repositories(){return <Shell kicker="REPOSITORY MAP" title="One ecosystem, explicit boundaries."><p className="lead">Current GitHub state was checked on 2026-09-24. Where a supplied historical baseline differed from the current main branch, the current branch was treated as authoritative.</p><div className="repo-grid">{repos.map(r=><RepoCard key={r.name} r={r}/>)}</div></Shell>}

export function PostV2(){return <Shell kicker="POST-V2" title="Enablement, adoption, production evidence."><p className="lead">Post-V2 is an execution program, not a new protocol version. V2 normative semantics remain frozen unless an explicit versioned successor is approved.</p><div className="post-grid"><article><span>PVE-1</span><h2>Ecosystem Enablement</h2><p>Quick starts, examples, profiles, tooling, fixtures and conformance harnesses to make external integration practical.</p><label>Evidence: integration path and executable examples</label></article><article><span>PVE-2</span><h2>Independent Adoption</h2><p>An independently maintained integration must be verified against canonical V2 contracts/vectors with exact-version evidence.</p><label>Status: evidence required for an actual independent implementation</label></article><article><span>PVE-3</span><h2>Production Evidence</h2><p>Real deployment evidence must identify implementation/version, contract/vector set, observed execution and audit evidence.</p><label>Status: deployment-gated; no live-provider claim is implied</label></article></div><div className="callout"><b>Evidence boundary</b><p>Foundation-owned reference implementations and CI establish engineering evidence. They do not by themselves establish independent adoption, production deployment, provider activation, regulatory certification, or target-environment readiness.</p></div></Shell>}
